services:
  app:
    build:
      context: ../
      dockerfile: config/Dockerfile
    container_name: blood-app
    env_file:
      - ../app.env
    networks:
      - deploy_net
    expose:
      - "8000"

networks:
  deploy_net:
    external: true
