---
- hosts: vps
  tasks:
    - name: Pull the latest changes and run the makefile
      shell: |
        cd ~/Blood-Transmutation && git pull origin master && make stop && make
      args:
        executable: /bin/bash
