---
- hosts: vps
  tasks:
    - name: Pull the latest changes and run the makefile
      shell: |
        cd ~/Blood-Transmutation && git pull origin main && make stop && make
      args:
        executable: /bin/bash
